#!/bin/bash

# gather input from the trackpad device 
# redirect it to the good or bad folder depending on the training purpose

# get category of training date, eg. good/bad
traintype=$1

# name training file
trainfile=$(mktemp -u -p $traintype --suffix .out evtest-`date +%F`-XXX)

# get device id use Touchpad string for a range of devices
deviceid=`xinput list | grep Touchpad | sed -e 's/^.*id=\([0-9][0-9]*\).*$/\1/'`

# get device path
devicepath=`xinput list-props $deviceid | awk -F\" '/Device Node/{print $2}'`

# gather training data
sudo evtest $devicepath > $trainfile
